In [45]:
import numpy as np
from time import time

In [46]:
print np.ones((5,4), dtype = np.int_)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [47]:
print np.random.rand(5,4)

[[ 0.97283744  0.71547057  0.24085506  0.07662769]
 [ 0.19078714  0.06733394  0.32892049  0.13444989]
 [ 0.06279585  0.52196666  0.0032542   0.73219264]
 [ 0.90140903  0.06962214  0.26717319  0.91699412]
 [ 0.04476341  0.43190781  0.26028302  0.06683923]]


In [48]:
# Sample Numbers from a Gaussian distribution
print np.random.normal(50,10,size=(2,3))
# Sample Random Integers in a 2D Array
a =  np.random.randint(0,10, size=(5,4))
print a

[[ 41.02954784  35.8211671   21.35557159]
 [ 50.09058733  52.59729604  58.9052606 ]]
[[6 0 3 1]
 [9 4 3 9]
 [2 1 7 6]
 [1 6 8 4]
 [2 6 7 8]]


In [49]:
# Attributes of an numpy array
print "Shape ->",a.shape     #Row , Col
print "Rows ->",a.shape[0]  #Row
print "Cols ->",a.shape[1]  #Col
print "Size ->",a.size      #No of Items R * C
print "DataType ->",a.dtype     

Shape -> (5, 4)
Rows -> 5
Cols -> 4
Size -> 20
DataType -> int64


In [50]:
#Calculations
print "Sum of Each Col ->", a.sum(axis=0)
print "Sum of Each Row ->", a.sum(axis=1)
print

print "Min of Each Col ->", a.min(axis=0)
print "Max of Each Row ->", a.max(axis=1)
print "Mean of all Ele ->", a.mean()
print 

print a.argmax()

Sum of Each Col -> [20 17 28 28]
Sum of Each Row -> [10 25 16 19 23]

Min of Each Col -> [1 0 3 1]
Max of Each Row -> [6 9 7 8 8]
Mean of all Ele -> 4.65

4


In [53]:
t1 = time()
print "ML4t"
t2 = time()
print "The time taken by print statement is ",t2 - t1,"sec"

ML4t
The time taken by print statement is  0.000401020050049 sec


In [56]:
print a[0,0]
print a[0][0]

6
6
